### ISSUE TITLE
Facing issues with node-sass where a gulp dependecy requires an older version

### ISSUE THREAD

**Issue by minouti** [driftyco/gulp-angular-seed#2]

**Comment by Ionitron** [comment]
Greetings @minouti!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
